### ISSUE TITLE
Crash when using certian sizes and gui scales

### ISSUE THREAD

**Issue by darkhax** [Wyn-Price/SkeletalBand#7]
```
Caused by: java.lang.ArithmeticException: / by zero
	at com.wynprice.boneophone.gui.GuiSelectList.render(GuiSelectList.java:61)
	at com.wynprice.boneophone.gui.GuiSelectMidis.func_73863_a(GuiSelectMidis.java:63)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	... 9 more
```

Edit: This actually happens every time I open the GUI for the band.

**Comment by Wyn-Price** [comment]
Is your screen height smaller than 40 pixels. That's the only way I can see something like this happening

**Comment by gegy1000** [comment]
On a 1920x1080 screen, it seems to happen on `GUI Scale: Large`, but not `GUI Scale: Auto`.

**Comment by darkhax** [comment]
Yes, gegy seems to be correct. I am using 1920x1080 on Gui Scale: Large.

**Comment by Wyn-Price** [comment]
This makes 0 sense.

**Comment by Wyn-Price** [comment]
New build pushed to curseforge. Waiting on them now
